### ISSUE TITLE
Weird issue

### ISSUE THREAD

**Issue by doggeddalle** [Clybius/ComfyUI-Extra-Samplers#11]
```
Traceback (most recent call last):
  File "E:\cunty\nodes.py", line 1889, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\cunty\custom_nodes\ComfyUI-Extra-Samplers\__init__.py", line 2, in <module>
    from . import nodes
  File "E:\cunty\custom_nodes\ComfyUI-Extra-Samplers\nodes.py", line 5, in <module>
    import comfy.sampler_helpers
ModuleNotFoundError: No module named 'comfy.sampler_helpers'

Cannot import E:\cunty\custom_nodes\ComfyUI-Extra-Samplers module for custom nodes: No module named 'comfy.sampler_helpers'
```

Started getting this on the recent pull. (IMPORT FAILED) as result.

Checked my packages and checked your requirements.txt to see if there was something new to install.. but everything seems ok. The module not found I assume relates to a package that I need but not sure what to do here to resolve issue.

**Comment by doggeddalle** [comment]
Updating ComfyUI has seemed to fix that issue. Updating Comfy also broke ComfyUI_smZNodes for anyone using that aswell.
